 export async function onRequestPost(context) {
  try {
    const body = await context.request.json();

    const businessName = body.businessName || "";
    const businessType = body.businessType || "";
    const location = body.location || "";
    const service = body.service || "";
    const extraDetails = body.extraDetails || "";

    if (!context.env.AI) {
      return Response.json(
        {
          error: "Workers AI binding is not configured."
        },
        {
          status: 500
        }
      );
    }

    // -----------------------------
    // CREATE SOCIAL MEDIA POST
    // -----------------------------

    const postPrompt = `
Write one short finished social media post for a UK local business.

Business name: ${businessName}
Business type: ${businessType}
Location: ${location}
Service: ${service}
Extra information: ${extraDetails}

Write approximately 60 to 100 words.

Requirements:
Use natural British English.
Start with a normal sentence, NOT hashtags.
Mention the business name.
Mention the service.
Include a clear call to action.
Finish with exactly 5 relevant hashtags.
Do not include explanations.
Do not include steps.
Do not include headings.
Do not include analysis.
Do not include notes.
Do not repeat the instructions.
Do not invent prices.
Do not invent phone numbers.
Do not invent awards or claims.

Return only the finished social media post.
`;

    const textResponse = await context.env.AI.run(
      "@cf/meta/llama-3.1-8b-instruct-fast",
      {
        prompt: postPrompt,
        max_tokens: 180
      }
    );

    let post =
      textResponse.response ||
      textResponse.result ||
      "";

    // -----------------------------
    // CLEAN AI TEXT
    // -----------------------------

    post = String(post).trim();

    // Remove explanations after separators
    if (post.includes("---")) {
      post = post.split("---")[0];
    }

    if (post.includes("## Step")) {
      post = post.split("## Step")[0];
    }

    // Remove strange repeated number output such as -1-0-0-0
    post = post.replace(/-1(?:-0){2,}.*$/s, "");

    // Remove common unwanted headings
    post = post.replace(/^#+\s*.*?\n+/g, "");

    post = post.replace(
      /^(final answer|final post|social media post|finished post)\s*:?\s*/i,
      ""
    );

    // Find hashtags generated by AI
    const hashtagMatches =
      post.match(/#[A-Za-z0-9_]+/g) || [];

    const uniqueHashtags = [];

    for (const tag of hashtagMatches) {
      if (
        !uniqueHashtags.some(
          existing =>
            existing.toLowerCase() === tag.toLowerCase()
        )
      ) {
        uniqueHashtags.push(tag);
      }

      if (uniqueHashtags.length === 5) {
        break;
      }
    }

    // Remove ALL hashtags from the main body
    post = post.replace(/#[A-Za-z0-9_]+/g, "");

    // Remove leftover whitespace
    post = post
      .replace(/[ \t]+/g, " ")
      .replace(/\n[ \t]+/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    // Create backup hashtags if AI failed to make 5
    const cleanBusinessName =
      businessName.replace(/[^A-Za-z0-9]/g, "");

    const cleanBusinessType =
      businessType
        .replace(/[^A-Za-z0-9 ]/g, "")
        .split(" ")
        .filter(Boolean)
        .join("");

    const cleanLocation =
      location.replace(/[^A-Za-z0-9]/g, "");

    const backupHashtags = [
      cleanBusinessName
        ? `#${cleanBusinessName}`
        : "#LocalBusiness",

      cleanLocation
        ? `#${cleanLocation}`
        : "#UKBusiness",

      cleanBusinessType
        ? `#${cleanBusinessType}`
        : "#LocalServices",

      "#SupportLocal",

      "#LocalBusiness"
    ];

    for (const tag of backupHashtags) {
      if (
        uniqueHashtags.length < 5 &&
        !uniqueHashtags.some(
          existing =>
            existing.toLowerCase() === tag.toLowerCase()
        )
      ) {
        uniqueHashtags.push(tag);
      }
    }

    uniqueHashtags.splice(5);

    // Add exactly 5 hashtags at the END
    post =
      post +
      "\n\n" +
      uniqueHashtags.join(" ");

    // -----------------------------
    // CREATE AI PICTURE
    // -----------------------------

    const safeBusinessType = businessType
      .replace(/[^\w\s-]/g, "")
      .slice(0, 80);

    const safeService = service
      .replace(/[^\w\s-]/g, "")
      .slice(0, 100);

    const safeLocation = location
      .replace(/[^\w\s-]/g, "")
      .slice(0, 60);

    const imagePrompt = `
Professional commercial photograph for a ${safeBusinessType} business.

Show the service: ${safeService}.

Location style: ${safeLocation || "United Kingdom"}.

Clean realistic professional advertising photography.
Square composition suitable for social media.
No written text.
No logos.
No prices.
No phone numbers.
No watermarks.
`;

    let image = "";

    try {
      const imageResponse = await context.env.AI.run(
        "@cf/black-forest-labs/flux-1-schnell",
        {
          prompt: imagePrompt,
          steps: 4
        }
      );

      if (imageResponse && imageResponse.image) {
        image =
          `data:image/jpeg;charset=utf-8;base64,${imageResponse.image}`;
      }

    } catch (imageError) {
      console.log(
        "Image generation failed:",
        imageError.message
      );
    }

    // -----------------------------
    // SEND RESULTS TO WEBSITE
    // -----------------------------

    return Response.json({
      success: true,
      result: post,
      image: image,
      imageGenerated: image !== ""
    });

  } catch (error) {
    console.log(
      "Generation error:",
      error.message
    );

    return Response.json(
      {
        error: "Something went wrong.",
        details: error.message
      },
      {
        status: 500
      }
    );
  }
}

